name: RenovateSample
targets:
  RenovateSample:
    type: application
    platform: iOS
    sources: RenovateSample
settings:
  base:
    APP_SHORT_VERSION: 0.0.0
    IPHONEOS_DEPLOYMENT_TARGET: 14.0
    SWIFT_VERSION: 5.5
schemes:
  RenovateSample:
    build:
      targets:
        RenovateSample: all
packages:
  PartialSheet:
    url: https://github.com/AndreaMiotto/PartialSheet.git
    exactVersion: 2.1.12
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    exactVersion: 4.2.1
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 8.15.0