name: Update Package.resolved when Renovate update project.yml

on:
  pull_request:
    types:
      - opened
    paths-ignore:
      - 'project.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No needs update-package-resolved required" '