name: Update Package.resolved

on:
  pull_request:
    branches:
      - 'renovate/**'
    paths:
      - '**/project.yml'

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.file_changes.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
  update:
    runs-on: macos-latest
    needs: precheck
    if: contains(fromJson(needs.precheck.outputs.files_changed), 'Package.resolved') == false
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild -resolvePackageDependencies
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Package.resolved
          file_pattern: Package.resolved
