name: Update Package.resolved when Renovate update project.yml

on:
  pull_request:
    paths:
      - 'project.yml'

jobs:
  get-file-changes:
    if: contains(github.head_ref, 'renovate')
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.file_changes.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
  update:
    runs-on: macos-latest
    needs: get-file-changes
    if: contains(fromJson(needs.get-file-changes.outputs.files_changed), 'Package.resolved') == false
    steps:
      - uses: actions/checkout@v3
      - run: make codegen
      - run: xcodebuild -resolvePackageDependencies
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Package.resolved
          file_pattern: Package.resolved
